---
language: csharp

git:
  depth: 1

dotnet: 2.1.502

matrix:
  fast_finish: true
  allow_failures:
  - stage: sanity testing
  - script: make sanity
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
    - os: osx
      osx_image: xcode9.4
      before_install:
        - brew cask install powershell
        - brew install hub 
      fast_finish: true

# travis-ci will quit using the cache if an enviroment variable changes.
# CACHE_VERSION is not used for anything other than invalidating the cache.
# DOTNET_SKIP_FIRST_TIME_EXPERIENCE is to skip the dotnet-cli initialization,
# which is expensive and unneeded for build agents.
env:
  global:
    - CACHE_VERSION=netcoreapp.2.1-sdk.2.1.502
    - POWERSHELL_TELEMETRY_OPTOUT=1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

install:
  - pwsh -f "${TRAVIS_BUILD_DIR}/.ci/install-dependencies.ps1"

before_script:
  - pwsh -f "${TRAVIS_BUILD_DIR}/build-module.ps1"

script: 
  - pwsh -Command "${TRAVIS_BUILD_DIR}\\.ci\\test.ps1" -Passwd "${passwd}" -User "${user}" -Server "${server}" 
  - pwsh -Command "${TRAVIS_BUILD_DIR}\\.ci\\integration-test.ps1" -Passwd "${passwd}" -User "${user}" -Server "${server}" -ClusterID "${clusterID}" 

deploy:
  provider: script
  script: pwsh -Command "${TRAVIS_BUILD_DIR}\\.ci\\upload-package.ps1" -ApiKey "${galleryKey}"
  on:
    branch: master
  

cache:
  timeout: 360
  directories:
    - $HOME/.nuget
    - deps